# Generated by Django 4.2.5 on 2023-10-07 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportedfire', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
