# Generated by Django 4.2.5 on 2023-10-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportedfire', '0002_delete_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(max_length=30)),
                ('lattitude', models.CharField(max_length=30)),
                ('fireimage', models.FileField(upload_to='fireimage/')),
            ],
        ),
    ]
